#!/bin/bash

if [ "$#" -gt "0" ]; then
  fileC=$1
  fileEXE=${fileC%.*}.exe
  shift
else
  echo "Usage: cmsTreeRun [your_analysis_file.C] [more_parameters]"
  exit
fi

ROOTLIBS="-L/usr/lib64 `$ROOTSYS/bin/root-config --glibs` -lMathCore -lMinuit"
ROOTINCDIR=`$ROOTSYS/bin/root-config --incdir`

rootcint -f CMSTreeDict.C -c MuonPogTree.h MuonPogTreeLinkDef.h

g++ -std=gnu++0x -I${ROOTINCDIR} ${fileC} CMSAnalysis.C CMSTreeDict.C ${ROOTLIBS} -lX11 -o ${fileEXE} 
./${fileEXE} "$@"

rm -f CMSTreeDict.C CMSTreeDict.h
rm -f ${fileEXE}
